language: r
cache: packages
pandoc_version: 2.9.2.1
addons:
  apt:
    packages:
    - ghostscript
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
install: travis_wait mvn install
env:
  global:
    secure: LLdUCbzESYonUARIyld30iYBp57bnasnyefCdlLevQYm/IFyDmE/ENGFUHIaSe5OAy6yBMdvRUOnmKV+b4zG7Q0DiPgo1O3butxWITJnziuxE9lw06bVExGBwkpO9X+F9pmxFyq4VOi+mehFZTH9/X6ES51M1414jiwdDH5vZpsuWWBHhTHXGYEW+uNcevkFV87cb+iiJ/UI+KuarP44DHuF5CeQuOsj0+XJBylFumvG8jksDwbym7eFjqTUjmxT3gc/9AuOT1rT55p9rdL/LUSpvJ1Bmopylk8v2z131gxB8/+I6CcBSZ6AJiBiccxOlvkzIUtXkU4muQw4Kt5US3nKiK0H9aTW/S8+hgPYMFwbXJnjkeyXsxT/iWf0Ka/oiYDMkhsgkBvULSYgXVgsisduN3FoTWdXJkp9M4Qt5h7bQ5DBFr7fh7tyMg6DVBd8OXip0d3wQHRdrEKo9WByOatbceemYYwGKtA3BzUQyuiB2bHbsGRw7f2Xrts8RYe9e4R/QUQ8UVCpMIEINyTBT9x4ucYOwluvdcZPimYxSyGYwMhqXyG+0AfGjPZogGYhjRmz6twf525a+IxfRvAK25GQ4IMvafqpPtchlQmU8hMNAwwU9raHdKwtl5k3mqYD1pMOfp288SwPbo17xA14jyzv+KCfmSoL3xPdbxvY91I=
