# Computer-based tasks

## Lab-based

### Psychophysics Toolbox

The PsychoPhysics Toolbox (PTB; https://psychtoolbox.org) is a free set of functions in MATLAB and an open source language with a syntax nearly identical to that of MATLAB called Octave (https://www.gnu.org/software/octave/). 
PTB was originally developed by vision scientists to conduct studies using psychophysical techniques using computer monitors.
Accordingly, PTB has functions that provide precise control over computer monitors, audio devices, and input devices like keyboards, mice, and button boxes.
The project is now open source.
Its repository is hosted on GitHub at https://github.com/Psychtoolbox-3/Psychtoolbox-3.

Peter Scarfe has created a set of tutorials for new PTB users. The tutorials may be found at https://peterscarfe.com/ptbtutorials.html.

For example, this absolutely minimal example of a script (https://peterscarfe.com/insertedCode/TotallyMinimalDemo.html) gives you a flavor of what PTB code looks and feels like.

```
% Clear the workspace and the screen
sca;
close all;
clear;

% Here we call some default settings for setting up Psychtoolbox
PsychDefaultSetup(2);

% Get the screen numbers. This gives us a number for each of the screens
% attached to our computer.
screens = Screen('Screens');

% To draw we select the maximum of these numbers. So in a situation where we
% have two screens attached to our monitor we will draw to the external
% screen.
screenNumber = max(screens);

% Define black and white (white will be 1 and black 0). This is because
% in general luminace values are defined between 0 and 1 with 255 steps in
% between. With our setup, values defined between 0 and 1.
white = WhiteIndex(screenNumber);
black = BlackIndex(screenNumber);

% Do a simply calculation to calculate the luminance value for grey. This
% will be half the luminace value for white
grey = white / 2;

% Open an on screen window using PsychImaging and color it grey.
[window, windowRect] = PsychImaging('OpenWindow', screenNumber, grey);

% Now we have drawn to the screen we wait for a keyboard button press (any
% key) to terminate the demo.
KbStrokeWait;

% Clear the screen.
sca;
```

### PsychoPy

<http://www.psychopy.org>

## Online

### Pavlovia

<https://github.com/psu-psychology/psychopy_pavlovia_workshop>

### Mechanical Turk

<https://psiturk.org>

### jsPsych

<https://www.jspsych.org/7.2/>

### LookIt

